# Generated by Django 3.0.5 on 2020-05-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mov', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del moviment', max_digits=8)),
                ('dataMoviment', models.DateField(help_text='Data del moviment')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mov.Caixa')),
                ('detallMoviment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mov.DetallMoviment')),
                ('formaPagament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mov.FormaPagament')),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Moviments',
                'unique_together': {('dataMoviment', 'detallMoviment', 'formaPagament', 'caixa')},
            },
        ),
    ]
