# Generated by Django 3.0.5 on 2020-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviment',
            unique_together=set(),
        ),
    ]
