# Generated by Django 3.0.5 on 2020-06-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0004_auto_20200616_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviment',
            options={'verbose_name_plural': 'Moviments'},
        ),
    ]
