# Generated by Django 3.0.5 on 2020-06-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsexExt',
        ),
    ]
