# Generated by Django 3.0.5 on 2020-05-17 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupMoviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(help_text='Descripcio del grup de Moviment', max_length=100, unique=True)),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grups de Moviment',
            },
        ),
        migrations.CreateModel(
            name='SubgrupMoviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(help_text='Descripci� del subgrup de Moviment', max_length=100)),
                ('grupMoviment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mov.GrupMoviment')),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subgrups de Moviment',
                'unique_together': {('grupMoviment', 'descripcio')},
            },
        ),
        migrations.CreateModel(
            name='FormaPagament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(help_text='Descripci� de la forma de pagament', max_length=100, unique=True)),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Formes de pagament',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(help_text='Descripci� de la caixa', max_length=100, unique=True)),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Caixes',
            },
        ),
        migrations.CreateModel(
            name='DetallMoviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.BooleanField(default=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataModificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(help_text='Descripci� del detall de moviment', max_length=100)),
                ('subgrupMoviment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mov.SubgrupMoviment')),
                ('usuariCreacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuariModificacio', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalls de Moviment',
                'unique_together': {('subgrupMoviment', 'descripcio')},
            },
        ),
    ]
