# Generated by Django 3.0.5 on 2020-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['descripcio'], 'verbose_name_plural': 'Caixes'},
        ),
        migrations.AlterModelOptions(
            name='detallmoviment',
            options={'ordering': ['descripcio'], 'verbose_name_plural': 'Detalls de Moviment'},
        ),
        migrations.AlterModelOptions(
            name='formapagament',
            options={'ordering': ['descripcio'], 'verbose_name_plural': 'Formes de pagament'},
        ),
        migrations.AlterModelOptions(
            name='grupmoviment',
            options={'ordering': ['descripcio'], 'verbose_name_plural': 'Grups de Moviment'},
        ),
        migrations.AlterModelOptions(
            name='subgrupmoviment',
            options={'ordering': ['descripcio'], 'verbose_name_plural': 'Subgrups de Moviment'},
        ),
        migrations.AddField(
            model_name='grupmoviment',
            name='color',
            field=models.CharField(blank=True, help_text='Color del grup de moviment', max_length=10, null=True),
        ),
    ]
