# Generated by Django 3.0.5 on 2020-05-31 10:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0002_auto_20200531_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupmoviment',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
