# Generated by Django 3.0.5 on 2020-05-31 20:56

from django.db import migrations, models
import mov.models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0003_auto_20200531_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupmoviment',
            name='color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7, null=True, validators=[mov.models.validate_color]),
        ),
    ]
