# Generated by Django 3.0.5 on 2020-06-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0004_auto_20200531_2256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallmoviment',
            unique_together=set(),
        ),
    ]
