# Generated by Django 3.0.5 on 2020-06-01 13:13

from django.db import migrations, models
import mov.models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0006_auto_20200601_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7, null=True, validators=[mov.models.validate_color]),
        ),
    ]
